Repository SD-woomool/SpringServer, pull requests merged in 2022-02, with the labels that each got.

#22 mysql, redis, spring 도커파일 설정 및 데이터베이스 mysql로 변경
  Dockerfile
  README.md
  build.gradle
  dockerfiles/mysql/Dockerfile
  dockerfiles/redis/Dockerfile
  src/main/resources/application-dev.yml
Labels: dev

#23 feature: 카카오에서 검색하고 디비에 저장
  src/main/java/app/joycourse/www/prod/config/PlaceRequestConfig.java
  src/main/java/app/joycourse/www/prod/controller/CourseController.java
  src/main/java/app/joycourse/www/prod/controller/ErrorController.java
  src/main/java/app/joycourse/www/prod/domain/CourseDetail.java
  src/main/java/app/joycourse/www/prod/domain/Place.java
  src/main/java/app/joycourse/www/prod/dto/PlaceInfoDto.java
  src/main/java/app/joycourse/www/prod/dto/PlaceSearchResponseDto.java
  src/main/java/app/joycourse/www/prod/filter/AuthorizationFilter.java
  src/main/java/app/joycourse/www/prod/repository/AccountRepository.java
  src/main/java/app/joycourse/www/prod/repository/JpaAccountRepository.java
  src/main/java/app/joycourse/www/prod/repository/JpaCourseDetailRepository.java
  src/main/java/app/joycourse/www/prod/repository/JpaCourseRepository.java
  src/main/java/app/joycourse/www/prod/repository/JpaPlaceRepository.java
  src/main/java/app/joycourse/www/prod/repository/MemoryPlaceCacheRepository.java
  src/main/java/app/joycourse/www/prod/repository/PlaceCacheRepository.java
  src/main/java/app/joycourse/www/prod/repository/PlaceRepository.java
  src/main/java/app/joycourse/www/prod/service/CourseService.java
  src/main/java/app/joycourse/www/prod/service/JwtService.java
  src/main/java/app/joycourse/www/prod/service/PlaceService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/app/joycourse/www/prod/controller/AccountControllerTests.java
Labels: dev

#26 feat: comment table, save comment 추가
  src/main/java/app/joycourse/www/prod/JoyCourseApplication.java
  src/main/java/app/joycourse/www/prod/controller/CommentController.java
  src/main/java/app/joycourse/www/prod/domain/Comment.java
  src/main/java/app/joycourse/www/prod/domain/Course.java
  src/main/java/app/joycourse/www/prod/domain/User.java
  src/main/java/app/joycourse/www/prod/dto/CommentInfoDto.java
  src/main/java/app/joycourse/www/prod/dto/CommentListDto.java
  src/main/java/app/joycourse/www/prod/dto/CommentSaveDto.java
  src/main/java/app/joycourse/www/prod/dto/CommentSaveRequestBodyDto.java
  src/main/java/app/joycourse/www/prod/dto/CourseInfoDto.java
  src/main/java/app/joycourse/www/prod/dto/CourseListDto.java
  src/main/java/app/joycourse/www/prod/filter/AuthorizationFilter.java
  src/main/java/app/joycourse/www/prod/repository/CommentRepository.java
  src/main/java/app/joycourse/www/prod/repository/JpaCommentRepository.java
  src/main/java/app/joycourse/www/prod/service/CommentService.java
  src/main/java/app/joycourse/www/prod/service/CourseService.java
  src/test/java/app/joycourse/www/prod/controller/AccountControllerTests.java
  src/test/java/app/joycourse/www/prod/controller/ExceptionTests.java
  src/test/java/app/joycourse/www/prod/repository/JpaAccountRepositoryTests.java
  src/test/java/app/joycourse/www/prod/service/AccountServiceTest.java
  src/test/java/app/joycourse/www/prod/service/CommentServiceTest.java
  src/test/resources/application.yml
Labels: dev

#35 Feature/apply feign
  build.gradle
  src/main/java/app/joycourse/www/prod/JoyCourseApplication.java
  src/main/java/app/joycourse/www/prod/config/KakaoApiClient.java
  src/main/java/app/joycourse/www/prod/config/PlaceRequestConfig.java
  src/main/java/app/joycourse/www/prod/controller/CourseController.java
  src/main/java/app/joycourse/www/prod/dto/PlaceSearchResponseDto.java
  src/main/java/app/joycourse/www/prod/service/PlaceService.java
  src/main/resources/application-dev.yml
Labels: enhancement

#37 fix: RedisTemplate -> RedisRepository
  src/main/java/app/joycourse/www/prod/config/RedisTemplateConfig.java
  src/main/java/app/joycourse/www/prod/controller/CourseController.java
  src/main/java/app/joycourse/www/prod/domain/Course.java
  src/main/java/app/joycourse/www/prod/domain/CourseDetail.java
  src/main/java/app/joycourse/www/prod/domain/Place.java
  src/main/java/app/joycourse/www/prod/domain/PlaceCache.java
  src/main/java/app/joycourse/www/prod/dto/CourseDetailDto.java
  src/main/java/app/joycourse/www/prod/dto/CourseInfoDto.java
  src/main/java/app/joycourse/www/prod/dto/PlaceInfoDto.java
  src/main/java/app/joycourse/www/prod/dto/PlaceSearchResponseDto.java
  src/main/java/app/joycourse/www/prod/repository/JpaPlaceRepository.java
  src/main/java/app/joycourse/www/prod/repository/PlaceRepository.java
  src/main/java/app/joycourse/www/prod/repository/RedisPlaceCacheRepository.java
  src/main/java/app/joycourse/www/prod/service/CourseService.java
  src/main/java/app/joycourse/www/prod/service/PlaceService.java
Labels: enhancement

#39 하드 코딩 및 cookie 제거
  src/main/java/app/joycourse/www/prod/annotation/resolver/AuthorizationUserResolver.java
  src/main/java/app/joycourse/www/prod/service/auth/ManageAuthService.java
Labels: bug, dev

#40 Feature/handle file
  build.gradle
  src/main/java/app/joycourse/www/prod/controller/CourseController.java
  src/main/java/app/joycourse/www/prod/controller/FileController.java
  src/main/java/app/joycourse/www/prod/dto/CourseDetailDto.java
  src/main/java/app/joycourse/www/prod/dto/CourseInfoDto.java
  src/main/java/app/joycourse/www/prod/dto/PhotoInfoDto.java
  src/main/java/app/joycourse/www/prod/entity/Course.java
  src/main/java/app/joycourse/www/prod/entity/CourseDetail.java
  src/main/java/app/joycourse/www/prod/entity/Place.java
  src/main/java/app/joycourse/www/prod/service/CourseService.java
  src/main/java/app/joycourse/www/prod/service/FileService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: dev
